const $ = (q, root=document) => root.querySelector(q);
const $$ = (q, root=document) => [...root.querySelectorAll(q)];

const icons = {
  dashboard:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>',
  users:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M22 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/></svg>',
  star:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polygon points="12 2 15 9 22 9 17 14 19 22 12 18 5 22 7 14 2 9 9 9 12 2"/></svg>',
  bell:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>',
  settings:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06A1.65 1.65 0 0 0 15 19.4a1.65 1.65 0 0 0-1 .6 1.65 1.65 0 0 0-.4 1.1V21a2 2 0 1 1-4 0v-.09A1.65 1.65 0 0 0 8 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.6 15a1.65 1.65 0 0 0-.6-1 1.65 1.65 0 0 0-1.1-.4H3a2 2 0 1 1 0-4h.09A1.65 1.65 0 0 0 4.6 8a1.65 1.65 0 0 0-.33-1.82l-.06-.06A2 2 0 1 1 7.04 3.3l.06.06A1.65 1.65 0 0 0 9 4.6a1.65 1.65 0 0 0 1-.6 1.65 1.65 0 0 0 .4-1.1V3a2 2 0 1 1 4 0v.09A1.65 1.65 0 0 0 15 4.6a1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9c.36.3.58.74.6 1.2H20a2 2 0 1 1 0 4h-.09A1.65 1.65 0 0 0 19.4 15z"/></svg>',
  user:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21a8 8 0 0 0-16 0"/><circle cx="12" cy="7" r="4"/></svg>',
  edit:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 20h9"/><path d="M16.5 3.5a2.1 2.1 0 0 1 3 3L7 19l-4 1 1-4 12.5-12.5z"/></svg>',
  info:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 16v-4"/><path d="M12 8h.01"/></svg>',
  chart:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 3v18h18"/><path d="m19 9-5 5-4-4-3 3"/></svg>',
  trash:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14H6L5 6"/><path d="M10 11v6"/><path d="M14 11v6"/><path d="M9 6V4h6v2"/></svg>',
  eye:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-7 11-7 11 7 11 7-4 7-11 7S1 12 1 12z"/><circle cx="12" cy="12" r="3"/></svg>',
  logout:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>',
  maximize:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M8 3H5a2 2 0 0 0-2 2v3"/><path d="M21 8V5a2 2 0 0 0-2-2h-3"/><path d="M3 16v3a2 2 0 0 0 2 2h3"/><path d="M16 21h3a2 2 0 0 0 2-2v-3"/></svg>',
  camera:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M23 7l-7 5 7 5V7z"/><rect x="1" y="5" width="15" height="14" rx="2"/></svg>',
  rocket:'<svg class="svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M5 15c-1 1-2 4-2 4s3-1 4-2"/><path d="M9 15l-4-4 8-8c4 0 8 4 8 8l-8 8-4-4z"/><path d="M15 9h.01"/></svg>'
};

const sensors = [
 ['Altura','m','rocket'],['Curvatura trayectoria','°/m','chart'],['Presión','bar','dashboard'],['Humedad','%','bell'],['Temperatura','°C','settings'],['Temp Micro ESP32','°C','settings'],['Gas','ppm','info'],['CO₂','ppm','info'],['Butano','ppm','info'],['Propano','ppm','info']
].map((s,i)=>({id:'s'+i,name:s[0],unit:s[1],icon:s[2],value:0,history:[]}));
const actuators = ['Bomba de presurización','Válvula de lanzamiento','Válvula de alivio','Servo de liberación','Propulsores auxiliares','Buzzer/Beacon','Cámara onboard','Sistema de recuperación'].map((name,i)=>({id:'a'+i,name,on:false,history:[]}));
let sponsors = [
 {name:'Sponsor 01',logo:''},{name:'Sponsor 02',logo:''},{name:'Sponsor 03',logo:''},{name:'Sponsor 04',logo:''}
];
let users = [
 {name:'Ana Tobar',email:'admin@condor.app',role:'Administrador',type:'Docente',permissions:'Total'},
 {name:'Lucas Rojas',email:'participante@condor.app',role:'Participante',type:'Alumno',permissions:'Lectura + gráficos'},
 {name:'Marta Gómez',email:'visitante@condor.app',role:'Participante',type:'Visitante',permissions:'Lectura limitada'}
];
let currentUser=null, chart=null, active='dashboard';
let deferredPrompt=null;
const SwalBase = (opts)=>Swal.fire({confirmButtonColor:'#45b9ad',background:getComputedStyle(document.body).getPropertyValue('--panel'),color:getComputedStyle(document.body).getPropertyValue('--text'),...opts});

function injectIcons(){ $$('[data-icon]').forEach(el=>el.innerHTML=icons[el.dataset.icon]||''); $('#themeIcon').textContent=document.body.classList.contains('dark')?'☀️':'🌙'; }
function navItems(){ const base=[['dashboard','Dashboard',icons.dashboard],['perfil','Mi Perfil',icons.user]]; if(currentUser?.role==='Administrador') base.push(['usuarios','Usuarios',icons.users],['sponsors','Sponsors',icons.star],['notificaciones','Notificaciones',icons.bell],['config','Configuración',icons.settings]); return base; }
function renderNav(){ $('#mainNav').innerHTML=navItems().map(([id,label,icon])=>`<button class="nav-btn ${active===id?'active':''}" data-page="${id}">${icon}<span class="nav-label">${label}</span></button>`).join(''); $$('.nav-btn').forEach(b=>b.onclick=()=>showPage(b.dataset.page)); }
function setTitle(t,sub=''){ $('#pageTitle').textContent=t; $('#pageSubtitle').textContent=sub; }
function showPage(page){ active=page; renderNav(); const map={dashboard:renderDashboard,usuarios:renderUsers,sponsors:renderSponsors,notificaciones:renderNotifications,config:renderConfig,perfil:renderProfile}; (map[page]||renderDashboard)(); }

function sensorValue(s){ let base={m:80,bar:4, '%':40, '°C':36, ppm:700, '°/m':12}[s.unit]||10; return +(base + Math.random()*base*.6).toFixed(s.unit==='bar'?2:1); }
function renderDashboard(){ setTitle('Dashboard General de Operaciones','Telemetría y control del cohete de propulsión por presión de agua'); $('#content').innerHTML=`
 <section class="panel"><div class="section-head"><div><h2>Cámaras en vivo</h2><p class="muted">Pegá URLs de YouTube/streaming. Luego podés reemplazar por feeds del ESP32-CAM o puente RTSP.</p></div></div><div class="grid cameras">${[1,2,3].map(i=>`<article class="camera-card"><div class="camera-head"><span class="sensor-icon">${icons.camera}</span><strong>Cámara ${i}</strong></div><input placeholder="URL de transmisión en vivo" data-cam="${i}"><button class="btn soft" onclick="previewCamera(${i})">Ver transmisión</button></article>`).join('')}</div></section>
 <section class="panel"><div class="section-head"><div><h2>Sensores</h2><p class="muted">Iconos inferiores: editar nombre, historial y gráfico.</p></div></div><div class="grid sensors" id="sensorGrid"></div></section>
 <section class="panel"><div class="section-head"><div><h2>Trayectoria y sensores en tiempo real</h2><p class="muted">Datos simulados listos para reemplazar por Supabase/ESP32.</p></div><select id="chartSensor" class="filter-date">${sensors.map(s=>`<option value="${s.id}">${s.name}</option>`).join('')}</select></div><div class="chart-wrap"><canvas id="telemetryChart"></canvas></div></section>
 <section class="panel"><div class="section-head"><h2>Actuadores</h2><button class="btn ghost" onclick="safeStop()">Parada segura</button></div><div class="grid actuators" id="actuatorGrid"></div></section>`;
 renderSensorCards(); renderActuatorCards(); makeChart(); }
function renderSensorCards(){ $('#sensorGrid').innerHTML=sensors.map(s=>`<article class="sensor-card"><div class="card-head"><span class="sensor-icon">${icons[s.icon]||icons.info}</span><div><h3>${s.name}</h3><div class="reading" id="val-${s.id}">${s.value} ${s.unit}</div></div></div><div class="card-actions"><button class="tiny-btn" title="Editar nombre" onclick="editSensor('${s.id}')">${icons.edit}</button><button class="tiny-btn" title="Historial" onclick="historySensor('${s.id}')">${icons.info}</button><button class="tiny-btn" title="Gráfico" onclick="selectChart('${s.id}')">${icons.chart}</button></div></article>`).join(''); }
function renderActuatorCards(){ $('#actuatorGrid').innerHTML=actuators.map(a=>`<article class="actuator-card"><h3>${a.name}</h3><p>Estado: <strong id="state-${a.id}">${a.on?'ON':'OFF'}</strong></p><button class="switch ${a.on?'on':''}" onclick="toggleActuator('${a.id}')"><span></span></button><div class="card-actions"><button class="tiny-btn" onclick="editActuator('${a.id}')">${icons.edit}</button><button class="tiny-btn" onclick="historyActuator('${a.id}')">${icons.info}</button></div></article>`).join(''); }
function makeChart(){ const ctx=$('#telemetryChart'); chart=new Chart(ctx,{type:'line',data:{labels:[],datasets:[{label:'Altura',data:[],tension:.35}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},scales:{x:{ticks:{color:getComputedStyle(document.body).getPropertyValue('--muted')}},y:{ticks:{color:getComputedStyle(document.body).getPropertyValue('--muted')}}},plugins:{legend:{labels:{color:getComputedStyle(document.body).getPropertyValue('--text')}}}}}); $('#chartSensor').onchange=e=>selectChart(e.target.value); }
function tick(){ sensors.forEach(s=>{s.value=sensorValue(s); s.history.push({date:new Date(),value:s.value}); const el=$(`#val-${s.id}`); if(el) el.textContent=`${s.value} ${s.unit}`;}); if(chart){ const s=sensors.find(x=>x.id===$('#chartSensor')?.value)||sensors[0]; chart.data.datasets[0].label=s.name; chart.data.labels.push(new Date().toLocaleTimeString()); chart.data.datasets[0].data.push(s.value); if(chart.data.labels.length>18){chart.data.labels.shift(); chart.data.datasets[0].data.shift();} chart.update('none'); }}

function editSensor(id){ const s=sensors.find(x=>x.id===id); SwalBase({title:'Editar sensor',input:'text',inputValue:s.name,showCancelButton:true}).then(r=>{if(r.isConfirmed&&r.value){s.name=r.value;renderSensorCards();SwalBase({icon:'success',title:'Sensor actualizado',timer:1200,showConfirmButton:false});}}); }
function historySensor(id){ const s=sensors.find(x=>x.id===id); const rows=s.history.slice(-12).reverse().map(h=>`<tr><td>${h.date.toLocaleDateString()}</td><td>${h.date.toLocaleTimeString()}</td><td>${h.value} ${s.unit}</td></tr>`).join(''); SwalBase({title:`Historial: ${s.name}`,html:`<input type="date" class="swal2-input"><div style="max-height:300px;overflow:auto"><table style="width:100%;text-align:left"><tr><th>Fecha</th><th>Hora</th><th>Valor</th></tr>${rows||'<tr><td colspan="3">Sin registros</td></tr>'}</table></div>`,width:700}); }
function selectChart(id){ $('#chartSensor').value=id; SwalBase({icon:'info',title:'Gráfico actualizado',text:'La línea muestra ahora el sensor seleccionado.',timer:1100,showConfirmButton:false}); }
function toggleActuator(id){ const a=actuators.find(x=>x.id===id); a.on=!a.on; a.history.push({date:new Date(),state:a.on?'ON':'OFF'}); renderActuatorCards(); SwalBase({icon:a.on?'success':'warning',title:`${a.name}: ${a.on?'ON':'OFF'}`,timer:1000,showConfirmButton:false}); }
function editActuator(id){ const a=actuators.find(x=>x.id===id); SwalBase({title:'Editar actuador',input:'text',inputValue:a.name,showCancelButton:true}).then(r=>{if(r.isConfirmed&&r.value){a.name=r.value;renderActuatorCards();}}); }
function historyActuator(id){ const a=actuators.find(x=>x.id===id); const rows=a.history.slice().reverse().map(h=>`<tr><td>${h.date.toLocaleDateString()}</td><td>${h.date.toLocaleTimeString()}</td><td>${h.state}</td></tr>`).join(''); SwalBase({title:`Historial ON/OFF: ${a.name}`,html:`<input type="date" class="swal2-input"><table style="width:100%;text-align:left"><tr><th>Fecha</th><th>Hora</th><th>Estado</th></tr>${rows||'<tr><td colspan="3">Sin registros</td></tr>'}</table>`,width:650}); }
function safeStop(){ actuators.forEach(a=>{a.on=false;a.history.push({date:new Date(),state:'OFF - Parada segura'});}); renderActuatorCards(); SwalBase({icon:'warning',title:'Parada segura ejecutada',text:'Todos los actuadores fueron apagados.'}); }
function previewCamera(i){ const url=$(`[data-cam="${i}"]`).value; SwalBase({title:`Cámara ${i}`,html:url?`<p>URL cargada:</p><code>${url}</code><p class="muted">Para YouTube embed usá formato /embed/VIDEO_ID.</p>`:'Cargá una URL de transmisión primero.',icon:url?'info':'warning'}); }

function renderUsers(){ setTitle('ABM de Usuarios','Gestión de perfiles, roles y permisos'); $('#content').innerHTML=`<section class="panel"><div class="section-head"><h2>Usuarios</h2><button class="btn primary" onclick="editUser()">${icons.edit} Nuevo usuario</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Nombre</th><th>Email</th><th>Rol</th><th>Tipo</th><th>Permisos</th><th>Acciones</th></tr></thead><tbody>${users.map((u,i)=>`<tr><td>${u.name}</td><td>${u.email}</td><td>${u.role}</td><td>${u.type}</td><td>${u.permissions}</td><td><div class="actions"><button class="btn soft" onclick="viewUser(${i})">${icons.eye} Ver</button><button class="btn soft" onclick="editUser(${i})">${icons.edit} Editar</button><button class="btn danger" onclick="deleteUser(${i})">${icons.trash} Eliminar</button></div></td></tr>`).join('')}</tbody></table></div></section>`; }
function viewUser(i){ const u=users[i]; SwalBase({title:u.name,html:`<b>Email:</b> ${u.email}<br><b>Rol:</b> ${u.role}<br><b>Tipo:</b> ${u.type}<br><b>Permisos:</b> ${u.permissions}`}); }
function editUser(i){ const u=users[i]||{name:'',email:'',role:'Participante',type:'Alumno',permissions:'Lectura'}; SwalBase({title:i==null?'Nuevo usuario':'Editar usuario',html:`<input id="uName" class="swal2-input" placeholder="Nombre" value="${u.name}"><input id="uEmail" class="swal2-input" placeholder="Email" value="${u.email}"><select id="uRole" class="swal2-input"><option ${u.role==='Administrador'?'selected':''}>Administrador</option><option ${u.role==='Participante'?'selected':''}>Participante</option></select><select id="uType" class="swal2-input"><option ${u.type==='Docente'?'selected':''}>Docente</option><option ${u.type==='Alumno'?'selected':''}>Alumno</option><option ${u.type==='Visitante'?'selected':''}>Visitante</option></select><input id="uPerm" class="swal2-input" placeholder="Permisos" value="${u.permissions}">`,showCancelButton:true,preConfirm:()=>({name:$('#uName').value,email:$('#uEmail').value,role:$('#uRole').value,type:$('#uType').value,permissions:$('#uPerm').value})}).then(r=>{if(r.isConfirmed){ if(i==null) users.push(r.value); else users[i]=r.value; renderUsers(); }}); }
function deleteUser(i){ SwalBase({title:'¿Eliminar usuario?',icon:'warning',showCancelButton:true,confirmButtonText:'Eliminar'}).then(r=>{if(r.isConfirmed){users.splice(i,1);renderUsers();}}); }

function renderSponsors(){ setTitle('Sponsors','Carga de datos y logos que se muestran en el footer'); $('#content').innerHTML=`<section class="panel"><div class="section-head"><h2>Sponsors</h2><button class="btn primary" onclick="editSponsor()">${icons.edit} Nuevo sponsor</button></div><div class="grid sensors">${sponsors.map((s,i)=>`<article class="mini-card"><div class="sponsor-logo">${s.logo?`<img src="${s.logo}" alt="${s.name}" style="max-width:100%;max-height:48px">`:s.name}</div><h3>${s.name}</h3><div class="actions"><button class="btn soft" onclick="viewSponsor(${i})">${icons.eye} Ver</button><button class="btn soft" onclick="editSponsor(${i})">${icons.edit} Editar</button><button class="btn danger" onclick="deleteSponsor(${i})">${icons.trash} Eliminar</button></div></article>`).join('')}</div></section>`; }
function refreshSponsors(){ $('#sponsorSlider').innerHTML=sponsors.map(s=>`<div class="sponsor-logo">${s.logo?`<img src="${s.logo}" alt="${s.name}" style="max-width:100%;max-height:48px">`:s.name}</div>`).join(''); }
function viewSponsor(i){ const s=sponsors[i]; SwalBase({title:s.name,html:`Logo URL: ${s.logo||'Sin logo cargado'}`}); }
function editSponsor(i){ const s=sponsors[i]||{name:'',logo:''}; SwalBase({title:i==null?'Nuevo sponsor':'Editar sponsor',html:`<input id="spName" class="swal2-input" placeholder="Nombre" value="${s.name}"><input id="spLogo" class="swal2-input" placeholder="URL del logo" value="${s.logo}">`,showCancelButton:true,preConfirm:()=>({name:$('#spName').value||'Sponsor',logo:$('#spLogo').value})}).then(r=>{if(r.isConfirmed){ if(i==null)sponsors.push(r.value); else sponsors[i]=r.value; refreshSponsors(); renderSponsors(); }}); }
function deleteSponsor(i){ sponsors.splice(i,1); refreshSponsors(); renderSponsors(); }

function renderNotifications(){ setTitle('Notificaciones','Alertas del sistema'); $('#content').innerHTML=`<section class="panel"><div class="section-head"><h2>Notificaciones</h2><button class="btn primary" onclick="sendAlert()">${icons.bell} Enviar alerta</button></div><div class="grid sensors">${['Sistema iniciado','Sensores conectados','Modo simulación activo'].map(t=>`<article class="mini-card"><h3>${t}</h3><p>${new Date().toLocaleString()}</p></article>`).join('')}</div></section>`; }
function sendAlert(){ SwalBase({icon:'success',title:'Alerta enviada',text:'La notificación fue registrada.'}); }
function renderConfig(){ setTitle('Configuración','Supabase, tema y parámetros generales'); $('#content').innerHTML=`<section class="panel"><h2>Configuración Supabase</h2><p class="muted">Editá estas constantes en js/app.js para producción:</p><pre>SUPABASE_URL = 'TU_URL';\nSUPABASE_ANON_KEY = 'TU_ANON_KEY';</pre><button class="btn primary" onclick="SwalBase({icon:'info',title:'Pendiente de conectar Supabase'})">Probar conexión</button></section>`; }
function renderProfile(){ setTitle('Mi Perfil','Editar datos personales'); $('#content').innerHTML=`<section class="panel profile-grid"><img id="profileBig" class="profile-big" src="${$('#profileImg').src}"><div class="form-grid"><label class="field">Nombre<input id="pName" value="${currentUser.name}"></label><label class="field">Email<input id="pEmail" value="${currentUser.email}"></label><label class="field">Rol<input value="${currentUser.role}" disabled></label><label class="field">Tipo<select id="pType"><option>Docente</option><option>Alumno</option><option>Visitante</option></select></label><button class="btn soft" onclick="$('#profileInput').click()">Cambiar foto</button><button class="btn primary" onclick="saveProfile()">Guardar perfil</button></div></section>`; $('#pType').value=currentUser.type||'Alumno'; }
function saveProfile(){ currentUser.name=$('#pName').value; currentUser.email=$('#pEmail').value; currentUser.type=$('#pType').value; $('#userName').textContent=currentUser.name; SwalBase({icon:'success',title:'Perfil guardado',timer:1200,showConfirmButton:false}); }

function loginAs(role){ currentUser = role==='admin'?{name:'Administrador',email:'admin@condor.app',role:'Administrador',type:'Docente'}:{name:'Participante',email:'participante@condor.app',role:'Participante',type:'Alumno'}; $('#loginScreen').classList.add('hidden'); $('#appShell').classList.remove('hidden'); $('#userName').textContent=currentUser.name; renderNav(); showPage('dashboard'); refreshSponsors(); setTimeout(()=>SwalBase({title:'Instalar CondorApp',text:'Podés instalar esta webapp como aplicativo en tu dispositivo.',icon:'info'}),300); }

$('#loginForm').onsubmit=e=>{e.preventDefault(); const email=$('#email').value; loginAs(email.includes('admin')?'admin':'participante');};
$$('[data-demo]').forEach(b=>b.onclick=()=>loginAs(b.dataset.demo==='admin'?'admin':'participante'));
$('#brandBtn').onclick=()=>$('#sidebar').classList.toggle('collapsed');
$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark'); localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light'); injectIcons(); if(active) showPage(active);};
$('#fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
$('#notifBtn').onclick=()=>showPage('notificaciones');
$('#logoutBtn').onclick=()=>SwalBase({title:'¿Salir?',showCancelButton:true,confirmButtonText:'Salir'}).then(r=>{if(r.isConfirmed) location.reload();});
$('#profileBtn').onclick=()=>$('#profileInput').click();
$('#profileInput').onchange=e=>{ const file=e.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{$('#profileImg').src=reader.result; const big=$('#profileBig'); if(big) big.src=reader.result; SwalBase({icon:'success',title:'Foto actualizada',timer:1000,showConfirmButton:false});}; reader.readAsDataURL(file); };
$('#installBtn').onclick=()=>{ if(deferredPrompt){deferredPrompt.prompt();} else SwalBase({icon:'info',title:'Instalación',text:'Usá el botón de instalación del navegador si está disponible.'}); };
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault(); deferredPrompt=e;});
if(localStorage.getItem('theme')==='dark') document.body.classList.add('dark');
injectIcons(); refreshSponsors(); setInterval(tick,1700);
if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{});

// Supabase: reemplazar por tus credenciales al conectar producción.
const SUPABASE_URL = 'https://wzsqorglemfedlrxowrs.supabase.co';
const SUPABASE_ANON_KEY = 'sb_publishable_q7x-_jYTNalYSYOMzQhw1w_V4ZVOMlL';
// const supabaseClient = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
