-- CondorApp v4 - Esquema Supabase inicial
-- Ejecutar en SQL Editor de Supabase. Ajustar políticas según entorno productivo.
create extension if not exists "pgcrypto";

create table if not exists public.profiles (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  name text not null,
  email text unique not null,
  role text not null check (role in ('Administrador','Participante')),
  participant_type text check (participant_type in ('Docente','Alumno','Visitante')),
  permissions text default 'Lectura',
  dni text,
  legajo text,
  certificates text,
  address text,
  province text,
  avatar_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.sensors (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  unit text not null,
  icon text,
  enabled boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  sensor_id uuid references public.sensors(id) on delete cascade,
  value numeric not null,
  recorded_at timestamptz default now()
);

create table if not exists public.actuators (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  name text not null,
  state boolean default false,
  enabled boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.actuator_history (
  id bigint generated by default as identity primary key,
  actuator_id uuid references public.actuators(id) on delete cascade,
  state boolean not null,
  event_label text,
  recorded_at timestamptz default now(),
  created_by uuid references public.profiles(id)
);

create table if not exists public.cameras (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  stream_url text not null,
  enabled boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.device_communication (
  id bigint generated by default as identity primary key,
  device_code text default 'ESP32-DEVKIT-V1',
  lora_status text,
  rssi numeric,
  snr numeric,
  packet_loss numeric,
  latency_ms integer,
  esp32_temp numeric,
  restart_count integer default 0,
  last_seen_at timestamptz default now(),
  recorded_at timestamptz default now()
);

create table if not exists public.device_events (
  id bigint generated by default as identity primary key,
  device_code text default 'ESP32-DEVKIT-V1',
  event_type text not null,
  detail text,
  recorded_at timestamptz default now()
);

create table if not exists public.remote_commands (
  id bigint generated by default as identity primary key,
  device_code text default 'ESP32-DEVKIT-V1',
  command text not null,
  payload jsonb default '{}'::jsonb,
  status text default 'pending' check (status in ('pending','sent','ack','failed')),
  requested_by uuid references public.profiles(id),
  created_at timestamptz default now(),
  ack_at timestamptz
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  title text not null,
  message text,
  is_read boolean default false,
  severity text default 'info' check (severity in ('info','success','warning','danger')),
  created_at timestamptz default now(),
  profile_id uuid references public.profiles(id)
);

create table if not exists public.sponsors (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  logo_url text,
  website_url text,
  description text,
  sort_order integer default 0,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

insert into public.sensors(code,name,unit,icon) values
('alt','Altura','m','rocket'),('curve','Curvatura trayectoria','°/m','chart'),('pressure','Presión','bar','dashboard'),('humidity','Humedad','%','bell'),('temperature','Temperatura','°C','temp'),('espTemp','Temp Micro ESP32','°C','settings'),('gas','Gas','ppm','info'),('co2','CO₂','ppm','info'),('butane','Butano','ppm','info'),('propane','Propano','ppm','info')
on conflict (code) do nothing;

insert into public.actuators(code,name) values
('pump','Bomba de presurización'),('launch_valve','Válvula de lanzamiento'),('relief_valve','Válvula de alivio'),('release_servo','Servo de liberación'),('aux_thrusters','Propulsores auxiliares'),('buzzer','Buzzer/Beacon'),('onboard_camera','Cámara onboard'),('recovery','Sistema de recuperación')
on conflict (code) do nothing;

insert into public.cameras(name,stream_url) values
('Cámara 1','https://www.youtube.com/embed/fO9e9jnhYK8?si=a_wBnZHHgW6gu94O'),('Cámara 2','https://www.youtube.com/embed/fO9e9jnhYK8?si=a_wBnZHHgW6gu94O'),('Cámara 3','https://www.youtube.com/embed/fO9e9jnhYK8?si=a_wBnZHHgW6gu94O');

insert into public.app_settings(key,value) values
('sponsor_slider','{"duration_seconds":22,"effect":"linear"}'::jsonb),
('lora','{"frequency":"915 MHz","spreading_factor":"SF7","bandwidth":"125 kHz","critical_rssi":-95}'::jsonb)
on conflict (key) do update set value=excluded.value, updated_at=now();

alter table public.profiles enable row level security;
alter table public.sensors enable row level security;
alter table public.sensor_readings enable row level security;
alter table public.actuators enable row level security;
alter table public.actuator_history enable row level security;
alter table public.cameras enable row level security;
alter table public.device_communication enable row level security;
alter table public.device_events enable row level security;
alter table public.remote_commands enable row level security;
alter table public.notifications enable row level security;
alter table public.sponsors enable row level security;
alter table public.app_settings enable row level security;

-- Políticas demo: lectura pública autenticada. Para producción, restringir escrituras a Administrador.
create policy if not exists "authenticated read profiles" on public.profiles for select to authenticated using (true);
create policy if not exists "authenticated read sensors" on public.sensors for select to authenticated using (true);
create policy if not exists "authenticated read sensor readings" on public.sensor_readings for select to authenticated using (true);
create policy if not exists "authenticated read actuators" on public.actuators for select to authenticated using (true);
create policy if not exists "authenticated read actuator history" on public.actuator_history for select to authenticated using (true);
create policy if not exists "authenticated read cameras" on public.cameras for select to authenticated using (true);
create policy if not exists "authenticated read communication" on public.device_communication for select to authenticated using (true);
create policy if not exists "authenticated read device events" on public.device_events for select to authenticated using (true);
create policy if not exists "authenticated read notifications" on public.notifications for select to authenticated using (true);
create policy if not exists "authenticated read sponsors" on public.sponsors for select to authenticated using (true);
create policy if not exists "authenticated read settings" on public.app_settings for select to authenticated using (true);
